[package]
name = "uuid_v1"
version = "0.1.0"
authors = ["Hong ChulJu <ang0123dev@gmail.com>"]

[dependencies]
lazy_static = "0.2.4"
uuid = "0.4"
rand = "0.3"
byteorder = "1"
chrono = "0.3.0"

[dependencies.interfaces]
git = "https://github.com/andrew-d/interfaces-rs.git"