[package]
name = "uuid_v1"
version = "0.1.2"
authors = ["Hong ChulJu <ang0123dev@gmail.com>"]
description = "UUID Version 1 implementation written in Rust"
license = "MIT"

[dependencies]
lazy_static = "0.2.4"
rand = "0.3"
byteorder = "1"
chrono = "0.3.0"
interfaces = "0.0.1"
